Models/Team.cs
using System.ComponentModel.DataAnnotations;

namespace CIDM_3312_Final_Project_1.Models;

public class Team
{
    public int TeamID {get; set;} // Primary Key

    [Display(Name = "Team Name")]
    public string team_name {get; set;} = string.Empty;
    public int Wins {get; set;}
    public int Losses {get; set;}
     public List<Player> Players {get; set;} = default!;
}

Pages/Teams/AddPlayer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using CIDM_3312_Final_Project_1.Models;

namespace CIDM_3312_Final_Project_1.Pages_Teams;

public class AddPlayerModel : PageModel
{
    private readonly AppDbContext _context;
    private readonly ILogger<AddPlayerModel> _logger;

    [BindProperty]
    public Player Player {get; set;} = default!;
    public SelectList TeamsDropDown {get; set;} = default!;



    public AddPlayerModel(AppDbContext context, ILogger<AddPlayerModel> logger)
    {
        _context = context;
        _logger = logger;
    }

    public void OnGet()
    {
        TeamsDropDown = new SelectList(_context.Teams.ToList(), "TeamID", "team_name");
    }

   public IActionResult OnPost()
    {
        if (!ModelState.IsValid)
        {
            var allErrors = ModelState.Values.SelectMany(v => v.Errors);
            foreach (var e in allErrors)
            {
                _logger.LogError($"Error: {e.ErrorMessage}");
            }
            return Page();
        }

        _context.Players.Add(Player);
        _context.SaveChanges();

        return RedirectToPage("./Index");
    }


}

Pages/Teams/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using CIDM_3312_Final_Project_1.Models;

namespace CIDM_3312_Final_Project_1.Pages.Teams
{
    public class CreateModel : PageModel
    {
        private readonly CIDM_3312_Final_Project_1.Models.AppDbContext _context;

        public CreateModel(CIDM_3312_Final_Project_1.Models.AppDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Team Team { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Teams.Add(Team);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Teams/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CIDM_3312_Final_Project_1.Models;

namespace CIDM_3312_Final_Project_1.Pages.Teams
{
    public class DeleteModel : PageModel
    {
        private readonly CIDM_3312_Final_Project_1.Models.AppDbContext _context;

        public DeleteModel(CIDM_3312_Final_Project_1.Models.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Team Team { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FirstOrDefaultAsync(m => m.TeamID == id);

            if (team is not null)
            {
                Team = team;

                return Page();
            }

            return NotFound();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team != null)
            {
                Team = team;
                _context.Teams.Remove(Team);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Teams/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CIDM_3312_Final_Project_1.Models;

namespace CIDM_3312_Final_Project_1.Pages.Teams
{
    public class DetailsModel : PageModel
    {
        private readonly CIDM_3312_Final_Project_1.Models.AppDbContext _context;

        public DetailsModel(CIDM_3312_Final_Project_1.Models.AppDbContext context)
        {
            _context = context;
        }

        public Team Team { get; set; } = default!;

        [BindProperty]
        public int PlayerIDToDelete {get; set;}


        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.Include(m => m.Players).FirstOrDefaultAsync(m => m.TeamID == id);



            if (team is not null)
            {
                Team = team;

                return Page();
            }

            return NotFound();
        }

        public IActionResult OnPostDeletePlayer(int? id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var review = _context.Players.FirstOrDefault(r => r.PlayerID == PlayerIDToDelete);
            if (review != null)
            {
                _context.Remove(review);
                _context.SaveChanges();
            }

            Team = _context.Teams.Include(m => m.Players).First(m => m.TeamID == id);
            return Page();
        }

    }
}

Pages/Teams/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CIDM_3312_Final_Project_1.Models;

namespace CIDM_3312_Final_Project_1.Pages.Teams
{
    public class EditModel : PageModel
    {
        private readonly CIDM_3312_Final_Project_1.Models.AppDbContext _context;

        public EditModel(CIDM_3312_Final_Project_1.Models.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Team Team { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team =  await _context.Teams.FirstOrDefaultAsync(m => m.TeamID == id);
            if (team == null)
            {
                return NotFound();
            }
            Team = team;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Team).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TeamExists(Team.TeamID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool TeamExists(int id)
        {
            return _context.Teams.Any(e => e.TeamID == id);
        }
    }
}

Pages/Teams/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CIDM_3312_Final_Project_1.Models;

namespace CIDM_3312_Final_Project_1.Pages.Teams
{
    public class IndexModel : PageModel
    {
        private readonly CIDM_3312_Final_Project_1.Models.AppDbContext _context;

        public IndexModel(CIDM_3312_Final_Project_1.Models.AppDbContext context)
        {
            _context = context;
        }

        public IList<Team> Team { get;set; } = default!;

        // Paging support
        // PageNum is the current page number we are on
        // PageSize is how many records will be displayed per page. 
        // PageNum needs BindProperty because the user decides which page we are on.
        // The user selects the page number
        // SupportsGet = true allows us to pass the PageNum through the URL with an HTTP Get Parameter 
        // This is necessary, because page numbers are not passed through normal forms
        [BindProperty(SupportsGet = true)]
        public int PageNum {get; set;} = 1;
        public int PageSize {get; set;} = 15;
        public int TotalPages {get; set;}

        // Sorting support
        [BindProperty(SupportsGet = true)]
        public string CurrentSort {get; set;} = string.Empty;

        // Search support
        [BindProperty(SupportsGet = true)]
        public string CurrentSearch {get; set;} = string.Empty;


        public async Task OnGetAsync()
        {
            var query = _context.Teams.Include(s => s.Players).Select(s => s);

            if (!string.IsNullOrEmpty(CurrentSearch))
            {
                query = query.Where(s => s.team_name.ToUpper().Contains(CurrentSearch.ToUpper()));
            }


            switch (CurrentSort)
            {
                case "first_asc":
                    query = query.OrderBy(s => s.team_name);
                    break;
                case "first_desc":
                    query = query.OrderByDescending(s => s.team_name);
                    break;
            }

            TotalPages = (int)Math.Ceiling(_context.Teams.Count() / (double)PageSize);

            Team = await query.Skip((PageNum-1)*PageSize).Take(PageSize).ToListAsync();
        }
    }
}

Pages/Teams/UpdatePlayer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using CIDM_3312_Final_Project_1.Models;
using Microsoft.EntityFrameworkCore;

namespace CIDM_3312_Final_Project_1.Pages_Teams;

public class UpdatePlayerModel : PageModel
{
    private readonly AppDbContext _context;
    private readonly ILogger<UpdatePlayerModel> _logger;

    [BindProperty]
    public Player Player {get; set;} = default!;

    public SelectList TeamsDropDown {get; set;} = default!;


    public UpdatePlayerModel(AppDbContext context, ILogger<UpdatePlayerModel> logger)
    {
        _context = context;
        _logger = logger;
    }

    public IActionResult OnGet(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var player = _context.Players.Find(id);
        if (player == null)
        {
            return NotFound();
        }
        else
        {
            Player = player;
        }

        TeamsDropDown = new SelectList(_context.Teams.ToList(), "TeamID", "team_name");


        return Page();
    }

    public IActionResult OnPost()
{
    if (!ModelState.IsValid)
    {
        var allErrors = ModelState.Values.SelectMany(v => v.Errors);
        foreach (var e in allErrors)
        {
            _logger.LogError($"Error: {e.ErrorMessage}");
        }
        return Page();
    }

    _context.Attach(Player).State = EntityState.Modified;
    _context.SaveChanges();

    TeamsDropDown = new SelectList(_context.Teams.ToList(), "TeamID", "Wins", "Losses");


    return RedirectToPage("./Index");
}


}

Pages/Teams/AddPlayer.cshtml
@page
@model CIDM_3312_Final_Project_1.Pages_Teams.AddPlayerModel

@{
    ViewData["Title"] = "Add Team Player";
}

<h1>Create</h1>

<h4>Team Player</h4>
<hr />
<form method="post">
    <div class="row mb-3">
        <div class="col-4">
            <label asp-for="Player.TeamID" class="control-label"></label>
            <select asp-for="Player.TeamID" asp-items="Model.TeamsDropDown" class="form-select">
                <option value="">Choose...</option>
            </select>
            <span asp-validation-for="Player.TeamID" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-4">
            <label asp-for="Player.player_name" class="form-label"></label>
            <input asp-for="Player.player_name" class="form-control">
            <span asp-validation-for="Player.player_name" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-4">
            <label asp-for="Player.ERA" class="form-label"></label>
            <textarea asp-for="Player.ERA" class="form-control"></textarea>
            <span asp-validation-for="Player.ERA" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-4">
            <label asp-for="Player.AVG" class="form-label"></label>
            <textarea asp-for="Player.AVG" class="form-control"></textarea>
            <span asp-validation-for="Player.AVG" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Teams/Create.cshtml
@page
@model CIDM_3312_Final_Project_1.Pages.Teams.CreateModel

        @{
        ViewData["Title"] = "Create";
        }
        
        <h1>Create</h1>
        
    <h4>Team</h4>
    <hr />
    <div class="row">
    <div class="col-md-4">
    <form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Team.team_name" class="control-label"></label>
                <input asp-for="Team.team_name" class="form-control" />
                <span asp-validation-for="Team.team_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Team.Wins" class="control-label"></label>
                <input asp-for="Team.Wins" class="form-control" />
                <span asp-validation-for="Team.Wins" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Team.Losses" class="control-label"></label>
                <input asp-for="Team.Losses" class="form-control" />
                <span asp-validation-for="Team.Losses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Teams/Delete.cshtml
@page
@model CIDM_3312_Final_Project_1.Pages.Teams.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Team</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Team.team_name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Team.team_name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Team.Wins)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Team.Wins)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Team.Losses)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Team.Losses)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Team.TeamID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Teams/Details.cshtml
@page
@model CIDM_3312_Final_Project_1.Pages.Teams.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Team</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Team.team_name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Team.team_name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Team.Wins)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Team.Wins)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Team.Losses)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Team.Losses)
        </dd>
        @foreach(var r in Model.Team.Players)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => r.player_name)
            </dt>
            <dd class="col-sm-10">
                <strong>@Html.DisplayFor(model => r.player_name): </strong> ERA: @Html.DisplayFor(model => r.ERA) AVG: @Html.DisplayFor(model => r.AVG)
                <br>
                <div class="row">
                    <div class="col-sm-auto">
                        <a asp-page="UpdatePlayer" asp-route-id="@r.PlayerID" class="btn btn-primary btn-sm">Update This Player</a>
                    </div>
                    <div class="col-sm-auto">
                        <form method="post">
                            <input type="hidden" asp-for="PlayerIDToDelete" value="@r.PlayerID">
                            <input type="submit" asp-page-handler="DeletePlayer" asp-route-id="@Model.Team.TeamID" value="Delete Review" class="btn btn-danger btn-sm">
                        </form>
                    </div>
                </div>
            </dd>

        }
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Team.TeamID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Teams/Edit.cshtml
@page
@model CIDM_3312_Final_Project_1.Pages.Teams.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Team</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Team.TeamID" />
            <div class="form-group">
                
                <label asp-for="Team.team_name" class="control-label"></label>
                <input asp-for="Team.team_name" class="form-control" />
                <span asp-validation-for="Team.team_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="Team.Wins" class="control-label"></label>
                <input asp-for="Team.Wins" class="form-control" />
                <span asp-validation-for="Team.Wins" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="Team.Losses" class="control-label"></label>
                <input asp-for="Team.Losses" class="form-control" />
                <span asp-validation-for="Team.Losses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Teams/Index.cshtml
@page
@model CIDM_3312_Final_Project_1.Pages.Teams.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
    <div class="row">
        <form class="d-flex" role="search" asp-page="./Index" method="get">
            <div class="col-3">
                <div class="input-group">
                    <span class="input-group-text"><i class="bi bi-search"></i></span>
                    <input class="form-control me-2" type="search" name="CurrentSearch" value="@Model.CurrentSearch" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @{
                    //Alternate sort order
                    var firstSort = "first_asc";
                    if (Model.CurrentSort == "first_asc")
                    {
                        firstSort = "first_desc";
                    }
                }
                <a asp-page="./Index" asp-route-CurrentSort="@firstSort" asp-route-PageNum="@Model.PageNum">@Html.DisplayNameFor(model => model.Team[0].team_name)</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Team[0].Wins)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Team[0].Losses)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.Team[0].Players)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Team) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.team_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wins)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Losses)
            </td>
            <td>
                @foreach(var r in item.Players)
                {
                    <p>@Html.DisplayFor(modelItem => r.player_name) <strong>ERA: @Html.DisplayFor(modelItem => r.ERA)</strong> <strong>AVG: @Html.DisplayFor(modelItem => r.AVG)</strong></p>
                }
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.TeamID">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.TeamID">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.TeamID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<hr />
@{
    // If we are on page 1, prevDisabled will be set to the "disabled" class
    // otherwise, it will be empty. So our previous button will be enabled or disabled based on this logic
    var prevDisabled = "";
    var nextDisabled = "";
    if (Model.PageNum <= 1)
    {
        prevDisabled = "disabled";
    }
    if (Model.PageNum >= Model.TotalPages)
    {
        nextDisabled = "disabled";
    }
}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item @prevDisabled"><a class="page-link" asp-page="./Index" asp-route-PageNum="@(Model.PageNum - 1)">Previous</a></li>
        <li class="page-item @nextDisabled"><a class="page-link" asp-page="./Index" asp-route-PageNum="@(Model.PageNum + 1)">Next</a></li>
    </ul>
</nav>

Pages/Teams/UpdatePlayer.cshtml
@page
@model CIDM_3312_Final_Project_1.Pages_Teams.UpdatePlayerModel

@{
    ViewData["Title"] = "Update Team Player";
}
<h1>Edit</h1>

<h4>Team Player</h4>
<hr />
<form method="post">
    <input type="hidden" asp-for="Player.PlayerID">
    <div class="row mb-3">
        <div class="col-4">
            <label asp-for="Player.TeamID" class="control-label"></label>
            <select asp-for="Player.TeamID" asp-items="Model.TeamsDropDown" class="form-select">
                <option value="">Choose...</option>
            </select>
            <span asp-validation-for="Player.TeamID" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-4">
            <label asp-for="Player.player_name" class="form-label"></label>
            <input asp-for="Player.player_name" class="form-control">
            <span asp-validation-for="Player.player_name" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-4">
            <label asp-for="Player.ERA" class="form-label"></label>
            <input asp-for="Player.ERA" class="form-control">
            <span asp-validation-for="Player.ERA" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-4">
            <label asp-for="Player.AVG" class="form-label"></label>
            <input asp-for="Player.AVG" class="form-control">
            <span asp-validation-for="Player.AVG" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}